name: Sync Repos

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync_repos:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Reference the stored token secret

    steps:
      # Step 1: Check out the repo for the GitHub Actions workflow
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install ungit using the curl method
      - name: Install ungit
        run: |
          curl -fsSL https://raw.githubusercontent.com/CooperDActor-bytes/ungit/refs/heads/main/install.sh | sudo bash

# Step 3: Download and De-gitrepo Repositories
- name: Download and De-gitrepo Repositories
  run: |
    REPOS=(
      "https://github.com/markondej/fm_transmitter"
      "https://github.com/pivpn/pivpn"
      "https://github.com/pi-hole/pi-hole"
      # Add more repositories here
    )
    FOLDERS=(
      "FMTransmitter"
      "vpn-pivpn"
      "pihole"
      # Add corresponding folders here
    )
    for i in "${!REPOS[@]}"
    do
      REPO=${REPOS[$i]}
      FOLDER=${FOLDERS[$i]}
      echo "Cloning repository: $REPO into folder $FOLDER"
      git clone $REPO $FOLDER
      cd $FOLDER
      # Run ungit with the deinit command on the current directory
      echo "Running ungit deinit on $FOLDER"
      ungit deinit .
      # Configure Git to use the GH_TOKEN for authentication
      git config --global user.email "cooper@salty.cool"
      git config --global user.name "CooperDActor-bytes"
      # Set the remote URL to use the GH_TOKEN
      git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/CooperDActor-bytes/pi-projects.git
      # Commit and push changes if necessary
      git add .
      git commit -m "Remove Git history"
      git push origin main
      cd ..
    done

