name: Sync Repos

on:
  schedule:
    # Run every 15 minutes
    - cron: "*/15 * * * *"
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  sync_repos:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repo for the GitHub Actions workflow
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install ungit using the curl method
      - name: Install ungit
        run: |
          curl -fsSL https://raw.githubusercontent.com/CooperDActor-bytes/ungit/refs/heads/main/install.sh | sudo bash

      # Step 3: Download and De-gitrepo Repositories
      - name: Download and De-gitrepo Repositories
        run: |
          REPOS=(
            "https://github.com/markondej/fm_transmitter"
            "https://github.com/pivpn/pivpn"
            "https://github.com/pi-hole/pi-hole"
            "https://github.com/rothgar/rpi-wordpress"
            "https://github.com/femto-code/Raspberry-Pi-Dashboard"
            "https://github.com/FreeTubeApp/FreeTube"
            "https://github.com/xbmc/xbmc.git"
            "https://github.com/Peppermint-Lab/peppermint"
            "https://github.com/go-gitea/gitea"
            "https://github.com/isc-projects/bind9"
            "https://github.com/mopidy/mopidy"
            "https://github.com/nextcloud/nextcloudpi"
            "https://github.com/googlecreativelab/coder/"
            "https://github.com/RaspberryPiFoundation/weather-station"
            "https://github.com/Moral355NG/32-bit-squadron"
            "https://github.com/CooperDActor-bytes/ungit"
          )
          FOLDERS=(
            "FMTransmitter"
            "vpn-pivpn"
            "pihole"
            "wp"
            "dashboard"
            "FreeYouTube"
            "Kodi"
            "peppermint-pi"
            "gittea"
            "Bind9-pi"
            "mopidly"
            "nextcloud"
            "GoogleCoder"
            "weatherstation"
            "32-bit-squadron"
            "ungit"
          )

          for i in "${!REPOS[@]}"
          do
            REPO=${REPOS[$i]}
            FOLDER=${FOLDERS[$i]}
            echo "Cloning repository: $REPO into folder $FOLDER"
            git clone $REPO $FOLDER
            cd $FOLDER
            # Run ungit with the deinit command to remove Git history
            echo "Running ungit deinit on $FOLDER"
            ungit deinit
            # Configure Git to use the GITHUB_TOKEN for authentication
            git config --global user.email "cooper@salty.cool"
            git config --global user.name "CooperDActor-bytes"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            # Commit and push changes if necessary
            git add .
            git commit -m "Remove Git history"
            git push origin main
            cd ..
          done

      # Step 4: Clean up if necessary
      # - name: Clean up
      #   run: |
      #     rm -rf ungit.tar.gz
